# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_sold', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=1000)),
                ('product_seller', models.CharField(default='ADMIN', max_length=20)),
            ],
        ),
    ]
